version: "2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    networks:
       - wp_net
  web:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=password
    networks:
       - wp_net
networks:
  wp_net:
    driver: overlay