version: "2"
services:
  php-fpm:
    volumes:
      - ./code:/usr/share/nginx/html
  web:
    volumes:
      - ./nginx/conf/mysite.template:/etc/nginx/conf.d/mysite.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"