version: "2"
services:
  #db:
  #  image: mysql:latest
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=password
  #    - MYSQL_DATABASE=mylamp
  php-fpm:
    build: ./docker/php-fpm
    image: bobbydvo/lemp_php-fpm:latest
    ports:
      - "9000:9000"
  web:
    build: ./docker/nginx
    image: bobbydvo/lemp_nginx:latest
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80